# Generated by Django 4.1 on 2022-08-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default='')),
                ('credit', models.BooleanField(default=None)),
                ('amount', models.FloatField(default=0.0)),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docReader.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docReader.user'),
        ),
    ]
